export type Post = {
  slug: string;
  title: string;
  description: string;
  date: string;
  readTime: string;
  category: string;
  content: Section[];
};

export type Section = {
  type: "h2" | "h3" | "p" | "ul" | "tip";
  text?: string;
  items?: string[];
};

export const POSTS: Post[] = [
  {
    slug: "how-to-find-a-job-in-spain-as-a-foreigner",
    title: "How to Find a Job in Spain as a Foreigner in 2026",
    description:
      "What the Spanish job market actually looks like from the inside. I recruit multilingual professionals for companies in Barcelona every week. Here is what works and what does not.",
    date: "2026-06-15",
    readTime: "7 min read",
    category: "Job Search",
    content: [
      { type: "p", text: "I recruit multilingual professionals for companies in Barcelona and across Spain every week. I know what lands and what gets skipped. This is not general advice. It is what I see in my inbox on a Tuesday morning." },
      { type: "h2", text: "How the Spanish job market actually works" },
      { type: "p", text: "Spain has two job markets running at the same time. The visible one, with ads on LinkedIn and Infojobs, and the one where most positions get filled before anyone posts anything. Personal connections, recruiter databases, internal referrals. If you are only applying to ads, you are looking at maybe 30% of what is actually available." },
      { type: "p", text: "Spanish companies also hire slowly. A process that takes two weeks in the UK can take eight in Spain. That silence in week three is not a rejection. It is Tuesday." },
      { type: "h2", text: "What Spanish recruiters look for on your CV" },
      { type: "p", text: "Spanish CVs have their own conventions and most international applicants do not know them." },
      { type: "ul", items: [
        "One or two pages. Clean layout, no heavy design.",
        "A professional summary at the top that says what you do and what you want.",
        "Results with numbers, not a list of things your job description said you were responsible for.",
        "Language skills with honest levels: B2, C1, native.",
        "Education after experience if you have more than three years of work history.",
      ]},
      { type: "p", text: "Spanish recruiters read fast. If your profile and the role do not connect in the first ten seconds, your application does not move. That is not harsh, that is just the reality when there are 200 CVs in a folder." },
      { type: "h2", text: "Do you need Spanish to work in Spain?" },
      { type: "p", text: "Depends entirely on the company and role. Tech companies and multinationals in Barcelona often run entirely in English. Customer-facing roles, SMEs, and anything in the public sector will want Spanish." },
      { type: "p", text: "Even basic Spanish helps. Not because it is required, but because it tells a recruiter you are planning to stay, not just passing through." },
      { type: "h2", text: "The mistakes I see most often" },
      { type: "ul", items: [
        "Sending the CV they used at home without changing anything. What reads well in the US or Brazil does not automatically read well in Spain.",
        "Applying on job boards and waiting. The most effective searches I see combine applications with direct outreach and a properly optimized LinkedIn profile.",
        "Underestimating the timeline. Most international professionals take three to six months to land a role in Spain. Starting with the right tools from day one matters.",
      ]},
      { type: "tip", text: "If you are applying from outside Spain, add one line somewhere in your profile or application that clarifies your right to work status and when you can start or relocate. Recruiters will not assume. Make it easy for them." },
      { type: "h2", text: "Where to actually look" },
      { type: "ul", items: [
        "LinkedIn: the most active platform for professional roles in Barcelona and Madrid.",
        "Infojobs: Spain's main local job board, most relevant for roles that require Spanish.",
        "Company career pages: many Spanish companies post roles only on their own websites.",
        "Recruitment agencies: a good recruiter in Spain can give you access to roles that never get advertised anywhere.",
      ]},
      { type: "h2", text: "What the candidates who land fast have in common" },
      { type: "p", text: "They know exactly which roles they are going for. They have adapted their documents to the local market. And they are not just applying and waiting. They are visible, they are reaching out, and they have a LinkedIn profile that shows up when a recruiter searches." },
      { type: "p", text: "Get those two things right before you start and you are already ahead of most people in the pile." },
    ],
  },
  {
    slug: "european-cv-vs-american-cv",
    title: "European CV vs American Resume: Key Differences Explained",
    description:
      "I review CVs for European companies every day. Here is exactly what changes when you move from an American resume to the European market, and what to remove before you send anything.",
    date: "2026-06-22",
    readTime: "6 min read",
    category: "CV Writing",
    content: [
      { type: "p", text: "Every week I receive CVs from professionals who have adapted a document built for the US or Canadian market and sent it to a company in Spain or Portugal. It looks fine to them. It reads wrong to the recruiter on the other side." },
      { type: "p", text: "I review CVs for European companies every day. Here is what actually needs to change." },
      { type: "h2", text: "Length" },
      { type: "p", text: "In the US, one page is almost always expected. In Europe, two pages is the norm for anyone with more than five years of experience. One page works for junior profiles. Three pages is almost never right unless you are in academia." },
      { type: "p", text: "Every line should be there for a reason. Two pages of substance beats one page of filler." },
      { type: "h2", text: "Format and design" },
      { type: "p", text: "European CVs are cleaner. Columns, icons, heavy graphics, unusual fonts most hiring managers in Spain, Portugal and Greece do not expect these and some find them distracting." },
      { type: "p", text: "ATS filters are also more common in European companies now. A heavily designed CV can fail the automated screen before a human ever opens it. Simple formatting is not boring. It is strategic." },
      { type: "h2", text: "Personal information" },
      { type: "ul", items: [
        "Name and professional email: always.",
        "LinkedIn URL: yes, if your profile is in good shape.",
        "City and country, or your target city if you are relocating.",
        "Phone number with country code.",
        "Date of birth and nationality: not required anywhere in Europe. Leave them out.",
        "Photo: not required in Spain, Portugal or Greece. Personal preference.",
      ]},
      { type: "h2", text: "The professional summary" },
      { type: "p", text: "American resumes often open with an objective statement about what the candidate is looking for. European CVs work better with a short professional summary: who you are, what you do, what you bring. Three to four lines, written for the role you are applying to." },
      { type: "tip", text: "A generic summary is one of the fastest ways to lose a recruiter in the first ten seconds. Write it for the specific role. Rewrite it every time you apply somewhere different." },
      { type: "h2", text: "Achievements, not responsibilities" },
      { type: "p", text: "This is where most CVs fall short, no matter which market they were written for. Listing what your job description said is not the same as showing what you did." },
      { type: "p", text: "European recruiters want numbers. Not 'Managed a sales team' 'Managed a team of eight and grew revenue by 34% in 18 months.' The specificity is what makes it land." },
      { type: "h2", text: "Language skills" },
      { type: "p", text: "Far more important here than on an American resume. List every language you actually speak with an honest level: native, fluent, professional working proficiency, or a CEFR level if you have a certificate." },
      { type: "p", text: "In Barcelona, Lisbon or Athens, a strong language section can be the thing that gets you the call over someone equally qualified." },
      { type: "h2", text: "What to cut before you send" },
      { type: "ul", items: [
        "The objective statement.",
        "References available upon request assumed in Europe, takes up space.",
        "GPA or university grades unless you graduated in the last two years.",
        "Extracurricular activities from university unless you are a recent graduate.",
        "Full street addresses or zip codes.",
      ]},
    ],
  },
  {
    slug: "what-european-recruiters-look-for-on-linkedin",
    title: "What European Recruiters Actually Look for on LinkedIn",
    description:
      "I use LinkedIn to find candidates for European companies every week. Here is exactly what I look at, in what order, and what makes me reach out or move on.",
    date: "2026-06-29",
    readTime: "5 min read",
    category: "LinkedIn",
    content: [
      { type: "p", text: "I use LinkedIn to find candidates for European companies every week. I am going to tell you exactly what I look at, in what order, and what makes me reach out or move on." },
      { type: "p", text: "Most LinkedIn advice is written by people who have never hired anyone. This is from the other side of the screen." },
      { type: "h2", text: "How I actually search" },
      { type: "p", text: "I use LinkedIn Recruiter with filters. Job title, location, language, keywords. Your profile has to contain the right words in the right places just to show up in results." },
      { type: "p", text: "If your headline says 'Open to opportunities' or 'Experienced professional', you are not appearing in my search. LinkedIn treats your headline as one of the most important keyword fields on your profile. Use it to say what you actually do." },
      { type: "h2", text: "The first five seconds" },
      { type: "p", text: "When I open a profile from a search result, I make a first decision fast. I check three things:" },
      { type: "ul", items: [
        "Your headline: does it match what I am looking for?",
        "Your location or open to work status: are you available in the market I am recruiting for?",
        "Your current or most recent role: is there a clear connection to what I am filling?",
      ]},
      { type: "p", text: "If any of those are unclear or do not match, I move on. Not because you are not qualified. Because I have 200 more profiles to review and I need clarity fast." },
      { type: "h2", text: "What makes me reach out" },
      { type: "ul", items: [
        "A headline with specific keywords that match the role.",
        "An About section that reads like a person wrote it, not a list of skills.",
        "Experience that shows what you achieved, not just where you worked.",
        "Language skills clearly listed. This matters a lot in Barcelona, Lisbon and Athens.",
        "Some activity on the platform. People who post or engage are easier to approach.",
      ]},
      { type: "tip", text: "Turn on Open to Work in private mode visible to recruiters but not your employer. That flag gets filtered in LinkedIn Recruiter searches. It immediately increases how often you show up." },
      { type: "h2", text: "The About section" },
      { type: "p", text: "Most About sections are empty or a copy-paste of the CV summary. Neither works." },
      { type: "p", text: "This is the one place on LinkedIn where you can write like a person. Use it to explain what you do, what kind of work you are good at, and what you are looking for. First person. Three to five short paragraphs. Done." },
      { type: "h2", text: "Keywords that matter in European recruiter searches" },
      { type: "ul", items: [
        "Exact job titles: 'Customer Success Manager', 'Financial Controller', 'Digital Marketing Specialist'.",
        "Language skills written out: 'native German speaker', 'fluent French', 'C1 Dutch'.",
        "Tools and platforms specific to your field.",
        "The cities or countries you are targeting.",
        "Certifications or qualifications relevant to your sector.",
      ]},
      { type: "h2", text: "The thing almost no one does" },
      { type: "p", text: "Set your location to your target city, not where you currently live. If you want to work in Barcelona, your profile should say Barcelona or your About section should mention you are relocating. Recruiters filter by location. A profile showing a city on another continent will not show up in a search for candidates in Europe." },
    ],
  },
  {
    slug: "mistakes-internationals-make-applying-in-europe",
    title: "The 7 Biggest Mistakes Internationals Make When Applying for Jobs in Europe",
    description:
      "I recruit for European companies and coach international professionals. These are the mistakes I see every week. They are specific, they are fixable, and most people do not know they are making them.",
    date: "2026-07-01",
    readTime: "8 min read",
    category: "Job Search",
    content: [
      { type: "p", text: "I recruit for European companies and coach international professionals. The same mistakes come up constantly. Not because people are not qualified. Because they are using an approach that does not work in this market." },
      { type: "p", text: "Here are the seven I see most often." },
      { type: "h2", text: "1. Sending the same documents they used at home" },
      { type: "p", text: "A CV built for the US, India or Brazil will not land the same way in Europe. The format is different. The length is different. The section order is different. The level of detail expected is different. European recruiters notice immediately when a document has not been adapted." },
      { type: "p", text: "Research the CV conventions for your target country, or get it rewritten by someone who actually works in that market." },
      { type: "h2", text: "2. Applying only through job boards and waiting" },
      { type: "p", text: "Job boards show a fraction of what is available. In many European markets, a large share of roles get filled through recruiter searches or personal referrals before anything ever gets posted. Applying on LinkedIn and waiting is a passive strategy in a market that rewards being visible and proactive." },
      { type: "p", text: "Combine applications with direct outreach. Make sure your LinkedIn profile shows up when a recruiter searches for someone like you." },
      { type: "h2", text: "3. Not being clear about the right to work" },
      { type: "p", text: "EU citizenship or the right to work in Europe is often the first filter a recruiter applies. If your application does not make your status clear, some will skip you rather than chase clarification." },
      { type: "p", text: "Add one line to your CV summary or cover letter. If you have EU citizenship, an EU partner visa, or a work permit, say so explicitly. Do not make the recruiter wonder." },
      { type: "h2", text: "4. A LinkedIn profile built for the wrong market" },
      { type: "p", text: "Your LinkedIn profile is how European recruiters find you passively. If it is not using the right keywords, showing the right location, and giving a clear picture of what you do, you are invisible in recruiter searches no matter how strong your background is." },
      { type: "p", text: "Treat your LinkedIn as seriously as your CV. Rewrite your headline with specific keywords. Update your location to your target city. Turn on Open to Work for recruiters." },
      { type: "h2", text: "5. Misjudging where their experience sits in the European market" },
      { type: "p", text: "This goes both ways. Someone with ten years of experience sometimes applies for roles two levels below where they should be targeting. Others apply for senior roles without realising their title does not carry the same seniority in European markets." },
      { type: "tip", text: "Check salary benchmarks and job title conventions for your target country before you start applying. A 'Senior Manager' in one market might be called a 'Director' in another and come with different expectations." },
      { type: "h2", text: "6. Giving up before the process has had time to work" },
      { type: "p", text: "European hiring is slower than most international candidates expect. A process that takes two weeks in the US can take eight in Spain or Portugal. Three weeks of silence is not a rejection. It is often just a Tuesday." },
      { type: "p", text: "Follow up professionally after two weeks with no response. Keep multiple applications active in parallel. Do not read silence as a no." },
      { type: "h2", text: "7. Not finding out why they are not getting replies" },
      { type: "p", text: "When the applications are going out and nothing is coming back, most people assume the market is hard or they need to apply more. Often the issue is something specific: a CV format that does not read right for this market, a LinkedIn profile that is not showing up in searches, a positioning that is not clear." },
      { type: "p", text: "Get a real review from someone who works in the European market. One conversation can explain months of silence." },
    ],
  },
  {
    slug: "how-to-prepare-for-a-job-interview-in-europe",
    title: "How to Prepare for a Job Interview in Europe as an International Candidate",
    description:
      "European interviews feel different from what most international candidates expect. A recruiter explains what companies actually assess, what questions to prepare for, and the mistakes that cost people the job.",
    date: "2026-07-06",
    readTime: "7 min read",
    category: "Job Search",
    content: [
      { type: "p", text: "Getting the interview is one thing. Knowing what to do when you get there is another." },
      { type: "p", text: "European interviews have their own rhythm and their own expectations. I work in recruitment and I have seen candidates with strong backgrounds lose offers because they prepared for the wrong kind of conversation. Here is what actually matters." },
      { type: "h2", text: "What European companies are actually assessing" },
      { type: "p", text: "Most international candidates assume the interview is about proving their technical skills. It is. But European hiring managers are also assessing something else: whether you understand the local market, whether you will fit the team, and whether you are genuinely committed to being here." },
      { type: "p", text: "For international candidates specifically, they are also trying to figure out: do you know what you are getting into? Have you done your research? Are you relocating for this role or just using it as a stepping stone?" },
      { type: "p", text: "These are not always asked directly. They come through in how you talk about the company, the role, and why you want to work in that country." },
      { type: "h2", text: "The questions you need to prepare for" },
      { type: "ul", items: [
        "Why do you want to work in Spain / Portugal / this country specifically? Have a real answer. Not 'I love the culture.' Something about the market, the industry, the opportunity.",
        "Why are you interested in this company? Read their website, their LinkedIn, their recent news. Name something specific.",
        "Tell me about yourself. This is not an invitation to recite your CV. It is your chance to tell a coherent story about where you have been and why this role is the next logical step.",
        "What are your salary expectations? Research the local market before the interview. Quoting a number based on your home country salary will almost always go wrong.",
        "Do you have the right to work in this country? If yes, say so immediately and clearly. It removes uncertainty and keeps the conversation moving.",
      ]},
      { type: "h2", text: "What is different about interviews in Spain, Portugal and Greece" },
      { type: "p", text: "Interviews in southern Europe tend to be more conversational than in the UK or the US. There is often more small talk at the start. The tone is warmer. This is not unprofessional — it is how these cultures build initial trust." },
      { type: "p", text: "Do not rush straight to your qualifications. Match the energy of the interviewer. If they want to talk for five minutes before getting into the questions, that is part of the process." },
      { type: "p", text: "Also expect the process to take longer. First interview, second interview, sometimes a third. This is normal. It does not mean they are unsure about you." },
      { type: "h2", text: "The preparation most candidates skip" },
      { type: "tip", text: "Before the interview, find the LinkedIn profiles of the people interviewing you. Look at their background, how long they have been at the company, what they post about. You will understand the culture better and it will show in how you ask questions at the end." },
      { type: "h2", text: "Questions to ask at the end" },
      { type: "p", text: "Most candidates ask about growth opportunities or company culture. These are fine but forgettable. Better questions:" },
      { type: "ul", items: [
        "What does success look like in this role after six months?",
        "What are the biggest challenges the team is facing right now?",
        "How did this position become available?",
        "What do you enjoy most about working here?",
      ]},
      { type: "p", text: "These show you are thinking about the job seriously, not just trying to get an offer." },
      { type: "h2", text: "After the interview" },
      { type: "p", text: "Send a short follow-up email the same day or the next morning. Three to four sentences. Thank them for their time, mention one specific thing from the conversation, and confirm your interest. Almost nobody does this in Europe. It will be noticed." },
    ],
  },
  {
    slug: "will-ai-replace-your-job-in-europe",
    title: "Will AI Replace Your Job in Europe? What International Professionals Need to Know",
    description:
      "Everyone is asking this question. Here is an honest answer from someone working inside European recruitment right now: what is actually changing, what is not, and what you should be doing about it.",
    date: "2026-07-04",
    readTime: "6 min read",
    category: "Job Search",
    content: [
      { type: "p", text: "This is the question I get more than any other right now. From candidates in my inbox, from professionals in sessions, from people who have been applying for months and are starting to wonder if the whole process has changed underneath them." },
      { type: "p", text: "I work in recruitment. I see what companies are actually doing. Not what they are announcing in press releases. What they are doing when they need to hire someone. Here is what is real and what is noise." },
      { type: "h2", text: "What AI is actually changing in hiring" },
      { type: "p", text: "ATS systems (the automated filters that screen CVs before a human sees them) have been around for years. AI is making them smarter. Some companies now use tools that scan for keyword matches, score candidates automatically, and flag profiles that do not fit a pattern." },
      { type: "p", text: "This means a CV that was written for a different market, or without the right terminology for the role, gets filtered out faster than before. Not because a recruiter decided you were not right. Because a system never passed you through." },
      { type: "p", text: "That part is real and it is already happening." },
      { type: "h2", text: "What AI is not replacing" },
      { type: "p", text: "The decision to hire someone is still made by a person. A hiring manager still has to meet you, read your presence in an interview, and decide if they want to work with you. AI is changing who gets seen. It is not changing who gets hired." },
      { type: "p", text: "It is also not replacing the things that make international candidates valuable in the first place. Language skills, cultural fluency, the ability to work across different contexts. These are specifically what AI cannot replicate and specifically what European companies are hiring for." },
      { type: "h2", text: "Which roles are actually at risk" },
      { type: "p", text: "Repetitive tasks. Data entry, basic content writing, template-heavy work, rule-based administrative processes. These are genuinely at risk and it would be dishonest to say otherwise." },
      { type: "p", text: "Roles that involve judgment, relationship-building, cultural navigation, complex communication, or working with ambiguity are far more resilient. This is not reassuring talk. It is what the hiring data actually shows." },
      { type: "h2", text: "What this means for your job search right now" },
      { type: "p", text: "If your CV is not written for the European market and optimized for ATS filters, you are more invisible than ever. The bar for getting through the automated screen has gone up, not down." },
      { type: "p", text: "If your LinkedIn profile does not use the exact keywords European recruiters search for, you are not appearing in searches at all. Not because you are unqualified. Because the system does not know you exist." },
      { type: "tip", text: "AI screening systems look for keyword matches between your profile and the job description. Read the job posting carefully and make sure the language in your CV mirrors the language in the role not synonyms, the exact terms they used." },
      { type: "h2", text: "The honest answer" },
      { type: "p", text: "AI is not going to replace your job in the next year if you are a skilled professional with real experience and the ability to work across cultures. But it is changing how you get found, how your application gets filtered, and how quickly the wrong document gets discarded." },
      { type: "p", text: "The professionals I see getting hired fast are not the ones ignoring these changes. They are the ones who understood the new rules and adapted their positioning accordingly. That is the part you can control." },
    ],
  },
  {
    slug: "bdm-jobs-switzerland-how-hiring-works",
    title: "BDM Jobs in Switzerland: What Nobody Tells You Before You Apply",
    description:
      "I recruit Business Development Managers for Swiss companies. Here is how hiring actually works in Switzerland, what gets your application read, and what gets it skipped.",
    date: "2026-07-27",
    readTime: "7 min read",
    category: "Job Search",
    content: [
      { type: "p", text: "I am currently filling BDM roles for companies based in the Neuchâtel and Vaud cantons. I review applications every week. And I keep seeing the same thing: strong candidates who do not get through, not because they are unqualified, but because they did not understand how the Swiss market works before they applied." },
      { type: "p", text: "This is what I would tell you before you send anything." },
      { type: "h2", text: "Switzerland is not one job market" },
      { type: "p", text: "The Swiss job market splits roughly by language region. French-speaking Switzerland (Geneva, Lausanne, Neuchâtel, the Vaud canton) operates differently from the German-speaking part. If you are applying to companies in the Romandie, French is often mandatory, not optional. German-speaking Switzerland will expect German even if the role is labelled English-friendly." },
      { type: "p", text: "The roles I am filling right now are in the French-speaking part. French plus English is the minimum for most of them. German adds real weight and in some cases is the deciding factor between two equally strong candidates." },
      { type: "h2", text: "What Swiss companies want in a BDM profile" },
      { type: "p", text: "Swiss hiring managers value precision over volume. They are not looking for someone who has done a bit of everything. They want someone who has done exactly what they need, in a technically similar environment, and has the numbers to prove it." },
      { type: "ul", items: [
        "New business acquisition experience — not just account management. The ability to open doors is valued separately from the ability to keep accounts.",
        "Documented results. Revenue figures, new logo wins, pipeline numbers. Vague descriptions of managing relationships do not land here.",
        "Technical credibility. Swiss companies in industrial sectors hire people who understand the product, not just people who can sell.",
        "Stability. A CV that shows two years here, eighteen months there, two years somewhere else will raise questions in Switzerland in a way it might not in other markets.",
      ]},
      { type: "h2", text: "The work permit question" },
      { type: "p", text: "This is the first thing I have to check for every candidate. Switzerland is not in the EU. A European passport (EU or EFTA) is required to obtain a Swiss work permit for most positions. A European residence permit alone is not the same thing and is not accepted." },
      { type: "p", text: "Frontier worker permits (Permis G) are available for candidates living in the French border departments (Ain, Haute-Savoie, Savoie, Isère) who work in Switzerland. If you live in one of those areas, you have more options than you might think." },
      { type: "p", text: "Some companies also have branches in Germany, the UK or France, which opens local contract arrangements for candidates based there. Worth asking about before you assume a Swiss-based role is out of reach." },
      { type: "tip", text: "Always state your work authorisation status on your CV or in your first message to a recruiter. It is the first thing we check and it saves time on both sides." },
      { type: "h2", text: "What the recruitment process looks like in Switzerland" },
      { type: "p", text: "Swiss hiring processes tend to be structured and thorough. Two or three rounds is normal. A pre-qualification call with the recruiter, a first interview with the hiring team, a second with management. The decisions are deliberate." },
      { type: "p", text: "This is not a market where you will get an offer in two weeks. Four to eight weeks from first contact to offer is common. The silence between rounds is rarely a bad sign. It is usually just how they work." },
      { type: "h2", text: "What gets your application read" },
      { type: "ul", items: [
        "A CV adapted to the European format — clean layout, two pages, results-focused experience section.",
        "Language skills stated clearly and honestly, with levels (B2, C1, native). Swiss recruiters will check.",
        "A specific note on your right to work status.",
        "A cover message or email that says exactly why this role and why now — not a generic introduction.",
      ]},
      { type: "h2", text: "What I am currently filling" },
      { type: "p", text: "Right now I have active mandates for BDM profiles in the Food & Beverage sector and in the semiconductor / electronic modules space, both based in the Neuchâtel and Vaud regions. If your background sits in technical B2B sales in either of those sectors and you hold an EU/EFTA passport, it is worth a conversation." },
      { type: "p", text: "The full role descriptions are on the Jobs page. You can apply directly by email — no form, no platform, just send me your CV and a short note." },
    ],
  },
  {
    slug: "independent-recruiter-stockholm-how-it-works",
    title: "Working with an Independent Recruiter in Stockholm: What Candidates Need to Know",
    description:
      "I am an independent recruiter based in Stockholm placing specialist profiles across Europe. Here is how working with a recruiter actually works, what to expect, and how to get the most out of it.",
    date: "2026-07-27",
    readTime: "6 min read",
    category: "Job Search",
    content: [
      { type: "p", text: "I get a lot of messages from people who are not quite sure how to work with a recruiter. What to send, when to follow up, whether it is worth reaching out if they do not see an exact match, whether the recruiter works for them or for the company." },
      { type: "p", text: "These are fair questions. Here is how it actually works, from my side of it." },
      { type: "h2", text: "What an independent recruiter does" },
      { type: "p", text: "I work with companies that need to hire specific profiles and do not want to use a large agency. They give me the mandate, I run the search, I manage the process from sourcing to offer. I am paid by the company when a hire is made." },
      { type: "p", text: "This means I am technically working for the company. But it also means I need to find the right candidate, which requires taking candidates seriously and being honest with them. If I send someone to a client who is not the right fit, I lose the relationship. The incentive is to find someone who actually works." },
      { type: "h2", text: "What you should send me" },
      { type: "p", text: "Your CV and a short paragraph on what you are looking for. That is it. I do not need a cover letter written specifically for me. I need to understand your background quickly and know whether it overlaps with anything I am working on." },
      { type: "p", text: "The CV should be in English unless I have specified otherwise. If you have relevant experience in technical B2B sales, financial markets, or specialist industrial sectors in Europe, your profile is likely relevant to something I have now or will have soon." },
      { type: "h2", text: "What happens after you contact me" },
      { type: "p", text: "If your profile is relevant to an active search, I will reply within 48 hours and we will have a short call. I use that call to understand your background better, explain the role, and be honest about whether there is a match. No one's time gets wasted." },
      { type: "p", text: "If you do not match anything current but your profile is strong, I keep it on file. This is not a polite no. I work on multiple mandates and new ones come in regularly. A profile I cannot use today might be exactly what I need in six weeks." },
      { type: "tip", text: "When you reach out to a recruiter, include one line on your right to work status in Europe. It is often the first question and it saves a round of messages." },
      { type: "h2", text: "What I am focused on right now" },
      { type: "p", text: "My current mandates are concentrated in Switzerland and Stockholm. On the Swiss side, I am placing specialist profiles in technical B2B sales and business development in industrial sectors. In Stockholm, I have an active search for a Scandinavian government bond broker for an established interdealer desk." },
      { type: "p", text: "Outside of active mandates, I work primarily with international professionals based in or targeting Northern and Western Europe. If your background is in technical sales, commercial roles, or financial markets and you are open to Switzerland, Sweden, France or the UK, it is worth being in touch." },
      { type: "h2", text: "What I cannot do" },
      { type: "p", text: "I cannot take a profile to a client if the work authorisation is not in place. I cannot introduce someone to a Swiss client without an EU or EFTA passport. I also cannot make promises about timelines — a process can move quickly or take months depending on the company." },
      { type: "p", text: "What I can do is be straightforward. If there is no match, I will say so. If there is, I will move quickly. That is about all anyone can promise." },
      { type: "h2", text: "How to find me" },
      { type: "p", text: "You can see my active mandates on the Jobs page and apply directly by email. Or if you want to send your profile for future opportunities, you can do that too. I am based in Stockholm, I work in English and Spanish, and I try to reply to every message." },
    ],
  },
  {
    slug: "jobbcoach-stockholm-karriarcoach-sverige",
    title: "Jobbcoach i Stockholm: Vad du behöver veta om karriärcoaching i Sverige",
    description:
      "Letar du efter en jobbcoach i Stockholm? Jag är karriärcoach och rekryterare baserad i Stockholm och hjälper internationella proffs att hitta jobb i Europa. Här är vad karriärcoaching faktiskt innebär och hur det fungerar.",
    date: "2026-08-10",
    readTime: "5 min läsning",
    category: "Karriärcoaching",
    content: [
      { type: "p", text: "Jag är jobbcoach och karriärcoach baserad i Stockholm. Jag arbetar också som rekryterare och placerar specialistprofiler hos europeiska företag varje vecka. Det är den kombinationen som gör skillnaden." },
      { type: "p", text: "De flesta karriärcoacher har aldrig anställt någon. Jag sitter på båda sidor av bordet." },
      { type: "h2", text: "Vad gör en jobbcoach?" },
      { type: "p", text: "En jobbcoach hjälper dig att förstå vad som faktiskt blockerar din jobbsökning och vad du ska göra åt det. Det kan handla om ditt CV, din LinkedIn-profil, hur du positionerar dig på marknaden, eller hur du söker jobb på ett sätt som faktiskt fungerar i Europa." },
      { type: "p", text: "Det är inte terapi och det är inte motiverande tal. Det är konkret, praktisk vägledning baserad på hur europeiska rekryterare faktiskt tänker och arbetar." },
      { type: "h2", text: "Vem söker karriärcoaching i Stockholm?" },
      { type: "ul", items: [
        "Internationella proffs som har bosatt sig i Sverige och vill ta sig in på den svenska arbetsmarknaden.",
        "Proffs som söker jobb i Europa från andra länder och inte förstår varför de inte får svar.",
        "Erfarna yrkesverksamma som vill byta bransch eller nivå och behöver hjälp att ompositionera sig.",
        "Kandidater som har starka meriter men vars CV och LinkedIn inte speglar det.",
      ]},
      { type: "h2", text: "Hur fungerar karriärcoaching hos mig?" },
      { type: "p", text: "Vi träffas på Google Meet. Du berättar var du befinner dig och vad som inte fungerar. Jag ställer frågor och vi går igenom vad som faktiskt blockerar dig. Du lämnar samtalet med en konkret handlingsplan, inte en lista med saker att tänka på." },
      { type: "p", text: "Jag arbetar på engelska och spanska. Sessioner kan bokas direkt via kontaktformuläret." },
      { type: "h2", text: "Vad är skillnaden mellan jobbcoach och karriärcoach?" },
      { type: "p", text: "I praktiken används begreppen ofta omväxlande. En jobbcoach fokuserar typiskt på den aktiva jobbsökningsprocessen: CV, ansökningar, intervjuer, strategi. En karriärcoach kan också hjälpa med bredare frågor om riktning, karriärväxling och långsiktig planering." },
      { type: "p", text: "Jag gör båda. Men det viktigaste jag tillför är perspektivet som aktiv rekryterare. Jag vet vad europeiska arbetsgivare letar efter för att jag söker dem varje dag." },
      { type: "tip", text: "Om du söker jobb i Sverige som utländsk medborgare: svenska är viktigt men inte alltid avgörande. Många internationella bolag i Stockholm rekryterar på engelska. Nyckeln är att förstå vilka bolag som matchar din profil och hur du når dem." },
      { type: "h2", text: "Vanliga frågor" },
      { type: "p", text: "Arbetar du bara med kandidater som söker jobb i Sverige? Nej. Jag arbetar med proffs som söker jobb i hela Europa: Schweiz, Frankrike, Sverige, Luxemburg och Storbritannien." },
      { type: "p", text: "Måste jag bo i Stockholm? Nej. Alla sessioner sker online. Jag har klienter i Europa, Mellanöstern, Latinamerika och Nordamerika." },
      { type: "p", text: "Hur lång tid tar det att se resultat? De flesta klienter börjar få svar inom två till fyra veckor efter att de implementerat förändringarna. Vissa snabbare. Det beror på bransch och hur aktiv marknaden är för din profil." },
    ],
  },
  {
    slug: "how-to-get-a-job-in-sweden-as-a-foreigner",
    title: "How to Get a Job in Sweden as a Foreigner in 2026",
    description:
      "I am a recruiter based in Stockholm. Here is what the Swedish job market actually looks like from the inside, what international candidates get wrong, and what gets applications read.",
    date: "2026-08-11",
    readTime: "7 min read",
    category: "Job Search",
    content: [
      { type: "p", text: "I live and work in Stockholm. I recruit multilingual professionals for European companies and coach international candidates through the job search process. I see the Swedish job market from both sides." },
      { type: "p", text: "Here is what actually works." },
      { type: "h2", text: "How the Swedish job market works" },
      { type: "p", text: "Sweden has a strong culture of flat hierarchies and consensus-based decision making. This affects how companies hire. Swedish employers are rarely in a hurry. A process that feels fast to a Swedish hiring manager can feel agonisingly slow to a candidate from the US or the Middle East." },
      { type: "p", text: "The most active platforms for professional roles are LinkedIn (by far the most used for international and specialist roles), Arbetsförmedlingen (the national employment agency, most relevant for Swedish-language roles), and company career pages." },
      { type: "h2", text: "Do you need Swedish to work in Sweden?" },
      { type: "p", text: "Depends on the employer and the role. Stockholm in particular has a large number of international companies, tech scale-ups, and multinationals that operate entirely in English. For those roles, Swedish is not a requirement." },
      { type: "p", text: "For SMEs, public sector roles, customer-facing positions, or companies outside the major cities, Swedish is almost always expected. Even a conversational level signals to an employer that you are committed to integrating, which matters more here than in some other markets." },
      { type: "h2", text: "What Swedish employers look for on your CV" },
      { type: "ul", items: [
        "Two pages maximum. Clean layout, no heavy design.",
        "A short professional summary at the top that says who you are and what you bring.",
        "Experience written as achievements with numbers, not a list of responsibilities.",
        "Language skills listed clearly with honest levels.",
        "Right to work status mentioned explicitly if you are a non-EU citizen applying from outside Sweden.",
      ]},
      { type: "p", text: "Swedish recruiters are practical and direct. They want to understand your background quickly and see evidence of results. Vague descriptions of team collaboration and stakeholder management without any numbers to back them up do not land well here." },
      { type: "h2", text: "What international candidates get wrong" },
      { type: "p", text: "The most common mistake I see: sending the same CV they used in their home market without adapting it. A CV built for the US, India or the Gulf will not automatically read well to a Swedish recruiter. The format is different, the expectations around what to include are different, and ATS systems are widely used here." },
      { type: "p", text: "The second most common mistake: relying only on job board applications. Sweden has a significant hidden job market. Personal networks, recruiter databases, and direct outreach to companies account for a large share of positions that never get advertised." },
      { type: "tip", text: "If you are relocating to Sweden or already here on a personal visa, state this on your CV. Employers worry about candidates who are geographically unstable. A line saying you are based in Stockholm or that you have residence in Sweden removes that uncertainty immediately." },
      { type: "h2", text: "Work permits and visas for Sweden" },
      { type: "p", text: "EU/EEA citizens do not need a work permit to work in Sweden. You can start working and register with the Swedish Tax Agency (Skatteverket) after arrival." },
      { type: "p", text: "Non-EU candidates need a work permit tied to a specific employer before they can start working. The employer initiates the application. This means most Swedish companies will only sponsor candidates they are very serious about, which raises the bar for non-EU applicants." },
      { type: "p", text: "Some roles, particularly in tech and senior specialist positions, do attract work permit sponsorship. But it adds complexity and you will be competing against candidates who already have the right to work." },
      { type: "h2", text: "The Swedish interview process" },
      { type: "p", text: "Swedish interviews tend to be structured, competency-based, and relatively low-pressure in tone. Expect questions about specific situations from your past work history using the STAR format (situation, task, action, result). Swedes are not easily impressed by self-promotion and find it slightly off-putting. Confidence through examples works better than direct claims about how good you are." },
      { type: "p", text: "Salary negotiation is expected and accepted. Research the market rate for your role and level before any interview. Saying 'whatever you think is fair' is not seen as humble, it is seen as unprepared." },
      { type: "h2", text: "Who gets hired fast in Sweden" },
      { type: "p", text: "Candidates with strong English (Sweden is among the highest-ranked non-native English speaking countries in the world, the standard is high), relevant technical or commercial experience, a CV adapted to the European format, and a clear story about why Sweden and why now." },
      { type: "p", text: "Some Swedish at even a basic level is a significant advantage wherever it is not strictly required. It tells employers you are here to stay." },
    ],
  },
  {
    slug: "career-coaching-vs-recruiter-difference",
    title: "Career Coach vs Recruiter: What Is the Difference and Which One Do You Need?",
    description:
      "Most people confuse career coaches and recruiters. They are not the same. Understanding the difference tells you exactly which one can help you right now — and what to do when you need both.",
    date: "2026-08-12",
    readTime: "6 min read",
    category: "Career Coaching",
    content: [
      { type: "p", text: "I am both. I work as a career coach and as an independent recruiter placing multilingual profiles for European companies. The question of which one someone needs comes up in almost every first conversation I have." },
      { type: "p", text: "Here is a clear answer." },
      { type: "h2", text: "What a recruiter does" },
      { type: "p", text: "A recruiter works for a company. They are hired by a business to find a specific person for a specific role. When you work with a recruiter, they are representing the employer, not you." },
      { type: "p", text: "This is not a bad thing. A good recruiter will be honest with you about whether your profile fits what they are looking for, give you useful feedback if it does not, and move quickly when it does. But the recruiter's job is to fill the role, not to manage your career." },
      { type: "p", text: "If a recruiter reaches out to you, it is because your profile matches something they are working on right now. If you reach out to a recruiter, you are hoping to match something they have or will have soon." },
      { type: "h2", text: "What a career coach does" },
      { type: "p", text: "A career coach works for you. They help you understand what is blocking your job search, how to position yourself, how to improve your documents, and how to approach the market in a way that actually gets results." },
      { type: "p", text: "Career coaching is not therapy. It is not motivational speaking. It is practical guidance on why your applications are not getting responses and what to do about it." },
      { type: "h2", text: "Which one do you need right now?" },
      { type: "ul", items: [
        "You need a recruiter if: you have a strong, market-ready profile, the right documents, and you are looking for someone who has direct access to roles that match your background.",
        "You need a career coach if: you are sending applications and not hearing back, your CV has not been adapted to the European market, your LinkedIn is not showing up in recruiter searches, or you are not sure what you are targeting.",
        "You need both if: you want to improve your documents and positioning at the same time as accessing live mandates.",
      ]},
      { type: "tip", text: "If a recruiter has never hired anyone, their coaching is theory. If a career coach has never worked inside a company's hiring process, their advice is also theory. When you are navigating a specific market, the most useful thing is working with someone who has done both." },
      { type: "h2", text: "Why most career coaches cannot tell you what European recruiters want" },
      { type: "p", text: "Most career coaches have built their practice around interview prep, mindset, and generic job search advice. That knowledge is fine, but it does not tell you what a recruiter in Zurich or Stockholm actually does when they open your CV on a Monday morning." },
      { type: "p", text: "I recruit for European companies every week. I know which CV formats get opened. I know which LinkedIn keywords get searched. I know what a Swiss hiring manager asks in a first call and what a French finance team values in a candidate profile. That context is not something you can get from someone who has not been inside the process." },
      { type: "h2", text: "The case for working with both at the same time" },
      { type: "p", text: "The candidates who move fastest are the ones who get their positioning right and have someone actively placing them. Better documents get you further with recruiters. Active recruiter relationships get you access to roles that never get posted." },
      { type: "p", text: "If you are targeting Europe and your background fits what I work on, there is a realistic version where I am coaching you and presenting you to companies at the same time. That is not a conflict of interest. That is just the most efficient path." },
      { type: "h2", text: "How to figure out what you need" },
      { type: "p", text: "Ask yourself one question: are you getting interviews? If yes, coaching on interview performance and salary negotiation is what moves the needle. If no, the problem is upstream: your documents, your positioning, your visibility to recruiters, or your targeting strategy." },
      { type: "p", text: "Most people who come to me are stuck in the second category. They are qualified. They are applying. They are not hearing back. The fix is almost always specific and fixable. But you have to know what you are fixing first." },
    ],
  },
  {
    slug: "how-to-get-a-job-in-germany-as-a-foreigner",
    title: "How to Get a Job in Germany as a Foreigner in 2026",
    description: "Germany is one of the most in-demand job markets in Europe for international professionals. But the hiring process is different from anywhere else. Here is what actually works, from someone who recruits for German companies.",
    date: "2026-08-15",
    readTime: "8 min read",
    category: "Job Search",
    content: [
      { type: "p", text: "Germany is hiring. The country has one of the lowest unemployment rates in Europe, a persistent skills shortage in engineering, tech, sales, and finance, and a government that has made it significantly easier for non-EU nationals to get a work visa in the last two years. If you have relevant experience and the right documents, Germany is genuinely one of the most accessible job markets in Europe right now." },
      { type: "p", text: "But the process is different. German companies hire deliberately. They move more slowly than you might expect, they care about specific things on your CV, and they have expectations around application materials that most international candidates do not know about until they have already made the mistake." },
      { type: "p", text: "I recruit senior commercial profiles across Europe, including Germany. Here is what I have seen work." },
      { type: "h2", text: "What German recruiters actually look for" },
      { type: "p", text: "German hiring is structured. Companies want to understand exactly what you did, in what context, with what result. Vague descriptions do not land well here. Neither does overselling." },
      { type: "ul", items: [
        "Specific achievements with numbers. Not responsibilities. What did you actually deliver?",
        "A clear career logic. Each role should make sense as a progression from the last.",
        "Qualifications listed precisely. German companies take education and certifications seriously. Include them clearly.",
        "Language levels stated honestly. B2, C1, native. German companies know what these mean.",
        "Right to work clarity. Make it easy for the recruiter. One line that says you have EU rights or that you are eligible for the Fachkrafteinwanderungsgesetz visa removes a major uncertainty.",
      ]},
      { type: "h2", text: "Do you need to speak German to get hired?" },
      { type: "p", text: "Less than you think, but more than zero." },
      { type: "p", text: "In tech, deep tech, engineering, and multinational commercial roles, many positions run entirely in English. Companies like SAP, Siemens, Bosch, and most venture-backed startups in Berlin and Munich operate in English internally and hire internationally without requiring German." },
      { type: "p", text: "That said, even conversational German changes how you are perceived. It signals that you plan to integrate, not just pass through. For any customer-facing role, regional sales, or positions in manufacturing or the Mittelstand (Germany's large mid-market sector), German is close to essential." },
      { type: "p", text: "If you are serious about Germany, starting German at B1 level opens a meaningfully larger set of roles." },
      { type: "h2", text: "The German CV: what is different" },
      { type: "p", text: "The German Lebenslauf has specific conventions and most international applicants do not follow them." },
      { type: "ul", items: [
        "A professional photo is standard in Germany. This surprises candidates from the UK or US, where photos are avoided. In Germany, a good headshot is expected.",
        "Personal details at the top: name, address, date of birth, nationality, and phone number. German applications are more detailed than most.",
        "Reverse chronological order, starting with your most recent role.",
        "A Deckblatt (cover page) for more traditional sectors like law, finance, or public institutions.",
        "Clean layout, no heavy graphics. German companies tend to read CVs for content, not design.",
      ]},
      { type: "tip", text: "If you are applying to a traditional German company or Mittelstand, write a proper cover letter (Anschreiben). It does not need to be long, but skipping it is noticed. For startups and tech companies, a short LinkedIn message or email is usually fine." },
      { type: "h2", text: "The visa situation in 2026" },
      { type: "p", text: "Germany introduced the Fachkrafteinwanderungsgesetz (Skilled Immigration Act) in 2023 and expanded it significantly in 2024. The short version: if you have a recognised qualification and a job offer, getting a work visa is now more straightforward than in most other EU countries." },
      { type: "p", text: "There is also the Chancenkarte (opportunity card), which allows skilled workers to come to Germany for up to a year to look for work without needing a job offer first. It is points-based and requires either a recognised qualification or significant work experience." },
      { type: "p", text: "EU nationals have full freedom of movement. If you are from outside the EU but have been living legally in another EU country for five years, you may have long-term resident status that simplifies things further." },
      { type: "h2", text: "Where to look for jobs in Germany" },
      { type: "ul", items: [
        "LinkedIn: most active for senior, commercial, and international roles. Recruiters are active here daily.",
        "XING: still used in Germany, especially for more traditional sectors and mid-market companies. Less important than it was, but worth having a profile.",
        "StepStone and Indeed Germany: the main local job boards for volume. Good for mid-level roles.",
        "Company career pages: many German companies, especially the Mittelstand, post roles only on their own websites and never on aggregators.",
        "Recruitment agencies: a good recruiter in Germany gives you access to positions that are never advertised. This is especially true for senior and specialist roles.",
      ]},
      { type: "h2", text: "The biggest mistakes international candidates make" },
      { type: "ul", items: [
        "Sending the same CV they use at home. German recruiters notice immediately when a CV was not adapted for the market.",
        "Applying without a cover letter to companies that expect one.",
        "Ignoring XING. If your target is a traditional German company, having no XING profile is a gap.",
        "Not addressing the language question. If you do not speak German, say so but explain what you bring in return. Silence on the topic creates uncertainty.",
        "Underestimating the timeline. German hiring processes are thorough. Four to eight weeks between application and offer is normal for mid to senior roles.",
      ]},
      { type: "h2", text: "What the candidates who land fast have in common" },
      { type: "p", text: "They are specific. They know which cities they are targeting (Berlin, Munich, Hamburg, Frankfurt all have very different job markets). They know which sectors are hiring. They have adapted their CV and LinkedIn to the German context before they start applying." },
      { type: "p", text: "And they are not waiting for the right ad to appear. They are reaching out directly, connecting with recruiters who place in their sector, and making themselves visible to the companies they want to work for." },
      { type: "p", text: "Germany rewards preparation. If you put in the work before you start, the market is more accessible than most people realise." },
    ],
  },
  {
    slug: "how-to-get-a-job-in-france-as-a-foreigner",
    title: "How to Get a Job in France as a Foreigner in 2026",
    description: "France has a reputation for being a difficult market for foreigners. Some of that reputation is earned. But the professionals who get hired know exactly why, and they prepare accordingly. Here is what works.",
    date: "2026-08-15",
    readTime: "7 min read",
    category: "Job Search",
    content: [
      { type: "p", text: "France is not the easiest job market in Europe for international professionals. There is a language barrier that is more real than in the Netherlands or Sweden. There is a hiring culture that values personal connections more than most. And there is a strong preference, in many sectors, for candidates who studied in France or have direct experience with French companies." },
      { type: "p", text: "None of that means it is closed. But it means you need to know what you are walking into." },
      { type: "p", text: "I place senior commercial profiles in France, including Technical Sales Managers and BDMs for companies in deep tech, semiconductors, and financial services. Here is what I have seen work for international candidates." },
      { type: "h2", text: "The honest truth about French and language" },
      { type: "p", text: "You need French. Not necessarily fluent French from day one, but you need to be working towards it and ideally already at B1 or B2 level before you start applying seriously." },
      { type: "p", text: "Paris has an international startup scene and a number of multinationals that operate in English. Roles at companies like Doctolib, Contentsquare, Qonto, or international banks in La Defense can be done in English. But the moment you move outside that bubble into French companies, regional offices, or any client-facing role, French is not optional." },
      { type: "p", text: "French professionals also tend to switch to French in meetings even when everyone agreed to use English. If you can follow a conversation and contribute, you will be taken more seriously than someone who needs everything translated." },
      { type: "h2", text: "What French recruiters look for on your CV" },
      { type: "p", text: "The French CV (curriculum vitae) has its own format and French recruiters read it differently from a British or American recruiter." },
      { type: "ul", items: [
        "One to two pages. Clean and clear. No heavy design unless you are in a creative field.",
        "A short profile or objective at the top, known as an accroche, that summarises what you offer.",
        "Results and achievements, not just responsibilities. French companies increasingly want to see what you delivered.",
        "Education is important in France, more so than in many other markets. Grandes Ecoles carry significant weight. If you studied at a well-regarded institution internationally, make sure it reads clearly.",
        "A photo is optional but common. Many French candidates include one.",
        "Language levels stated precisely. French companies want to know your actual level.",
      ]},
      { type: "h2", text: "The role of personal connections in France" },
      { type: "p", text: "France is a relationship-driven market. More than in most Northern European countries, who you know and who can vouch for you matters enormously in the hiring process." },
      { type: "p", text: "This does not mean you cannot get hired without connections. It means that building a network in France, even before you move, is worth the effort. LinkedIn is used, though less intensively than in the UK or Nordics. Attending industry events, reaching out directly to people in your sector, and building genuine relationships with French recruiters who specialise in your field will open more doors than job applications alone." },
      { type: "tip", text: "If you know anyone who works at a company you want to target, ask for an introduction rather than applying cold. A referred application in France moves significantly faster than one that arrives from a job board." },
      { type: "h2", text: "Where to look for jobs in France" },
      { type: "ul", items: [
        "LinkedIn: the most important platform for international and professional roles. Recruiters in France are active, especially for senior positions.",
        "Welcome to the Jungle: the leading job platform for French startups and scale-ups. Very active and well-designed.",
        "Apec: the main platform for cadre (professional/managerial) positions. Less known internationally but heavily used by French companies.",
        "Indeed France and Cadremploi: useful for volume and for more traditional sectors.",
        "Company career pages: large French companies like L'Oreal, TotalEnergies, BNP Paribas, and Airbus post many roles directly.",
      ]},
      { type: "h2", text: "The visa situation for non-EU nationals" },
      { type: "p", text: "France has a Talent Passport (Passeport Talent) scheme for skilled workers, which allows non-EU nationals with a job offer and relevant qualifications to get a multi-year residence and work permit. The process is handled by the employer and the French immigration authorities. It is more bureaucratic than Germany's equivalent but it works." },
      { type: "p", text: "EU nationals have full freedom of movement. If you are already in another EU country, moving to France for work requires only registering locally, not applying for a visa." },
      { type: "h2", text: "The biggest mistakes international candidates make" },
      { type: "ul", items: [
        "Assuming English is enough. Even in international companies, French matters more than the job ad suggests.",
        "Not adapting the CV to French format and expectations.",
        "Skipping the cover letter. The lettre de motivation is still expected in many French companies, especially larger ones.",
        "Applying only through job boards. The hidden market is significant in France. Direct outreach and recruiter relationships are essential.",
        "Underestimating the timeline. French hiring can move slowly. Six to ten weeks from application to offer is not unusual for senior roles.",
      ]},
      { type: "h2", text: "What works" },
      { type: "p", text: "The international professionals who get hired in France fast are the ones who treat the language as a non-negotiable and start working on it early. Who understand that Paris and Lyon and Toulouse have different markets. Who know which sectors are growing (French tech, clean energy, financial services, luxury, pharma) and position themselves clearly within one." },
      { type: "p", text: "And who build their presence deliberately: a LinkedIn profile that works in a French context, a CV adapted to local expectations, and a network that is not starting from zero on the day they decide to move." },
      { type: "p", text: "France rewards the candidates who did the preparation. The ones who show up without it tend to find the market harder than it needs to be." },
    ],
  },
];

export function getPost(slug: string): Post | undefined {
  return POSTS.find((p) => p.slug === slug);
}
